export const USER_LOGIN = 'USER_LOGIN';
export const USER_FACEBOOK_LOGIN = 'USER_FACEBOOK_LOGIN';
export const USER_GOOGLE_LOGIN = 'USER_GOOGLE_LOGIN';

export const USER_SIGN_UP = 'USER_SIGN_UP';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_GET = 'USER_GET';
export const USER_SET = 'USER_SET';

export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_SET = 'USER_UPDATE_SET';

export const SET_ACTIVE_USER = 'SET_ACTIVE_USER';

export const SET_LOADER = 'SET_LOADER';

export const GLOBAL_ERROR_SET = 'GLOBAL_ERROR_SET';

export const SIGNIN_ERROR_SET = 'SIGNIN_ERROR_SET';
export const SIGNUP_ERRORS_SET = 'SIGNUP_ERRORS_SET';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';

export const FORGOT_PASSWORD_ERROR_SET = 'FORGOT_PASSWORD_ERROR_SET';
export const RESET_PASSWORD_ERROR_SET = 'RESET_PASSWORD_ERROR_SET';

export const PASSWORD_CHANGE = 'PASSWORD_CHANGE';
export const PASSWORD_CHANGE_ERROR = 'PASSWORD_CHANGE_ERROR';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';

export const SOCIAL_LOGIN_ERROR_SET = 'SOCIAL_LOGIN_ERROR_SET';
export const SET_VERIFY_CODE_ERROR = 'SET_VERIFY_CODE_ERROR';
export const VERIFY_CODE = 'VERIFY_CODE';
export const UPDATE_NOTIFICATION_SETTINGS = 'UPDATE_NOTIFICATION_SETTINGS';
export const NOTIFICATION_SETTINGS_ERROR = 'NOTIFICATION_SETTINGS_ERROR';
export const NOTIFICATION_SETTINGS_SUCCESS = 'NOTIFICATION_SETTINGS_SUCCESS';
export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR'
export const TOGGLE_THEME = "TOGGLE_THEME"

export const SLIDE_SIGN_UP = "SLIDE_SIGN_UP"